export const PRODUCTS_FILTER_SORT_BY_SIZE = "PRODUCTS_FILTER_SORT_BY_SIZE"
export const PRODUCTS_FILTER_SORT_BY_PRICE = "PRODUCTS_FILTER_SORT_BY_PRICE"
export const PRODUCTS_CLEAR_FILTER_DATA = "PRODUCTS_CLEAR_FILTER_DATA"
